In [ ]:
"""
First autograd
"""
import torch

x = torch.tensor(3.0, requires_grad=True)

y = x ** 2

print(x)
print(y)

y.backward()

print(x.grad)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)
tensor(6.)


In [6]:
import torch

x = torch.tensor(2.0, requires_grad=True)

y = x ** 2 + 3 * x

print('Y: ', y)

y.backward()

print("gradient: ", x.grad)

Y:  tensor(10., grad_fn=<AddBackward0>)
gradient:  tensor(7.)


In [7]:
"""
Autograd — Multiple Variables
"""

import torch

x = torch.tensor(2.0, requires_grad=True)
w = torch.tensor(3.0, requires_grad=True)

y = x * w

print("y:", y)

y.backward()

print("gradient of x:", x.grad)
print("gradient of w:", w.grad)

y: tensor(6., grad_fn=<MulBackward0>)
gradient of x: tensor(3.)
gradient of w: tensor(2.)


In [8]:
"""
Loss Function
"""

prediction = torch.tensor(6.0)
actual = torch.tensor(10.0)

loss = (prediction - actual) ** 2

print("prediction: ", prediction)
print("actual: ", actual)
print("Loss: ", loss)

prediction:  tensor(6.)
actual:  tensor(10.)
Loss:  tensor(16.)


In [9]:
import torch

x = torch.tensor(2.0)
w = torch.tensor(3.0, requires_grad=True)

actual = torch.tensor(10.0)

prediction = x * w

loss = (prediction - actual) ** 2

print("Prediction:", prediction)
print("Loss:", loss)

loss.backward()

print("Gradient of w:", w.grad)

Prediction: tensor(6., grad_fn=<MulBackward0>)
Loss: tensor(16., grad_fn=<PowBackward0>)
Gradient of w: tensor(-16.)


In [4]:
import torch

x = torch.tensor(4.0, requires_grad=True)

y = x ** 2

y.backward()

print(y)
print("gradient: ", x.grad)


tensor(16., grad_fn=<PowBackward0>)
gradient:  tensor(8.)


In [10]:
import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(5,4),
    nn.ReLU(),
    nn.Linear(4,3),
    nn.ReLU(),
    nn.Linear(3,1)
)

print(model)

x = torch.tensor([[2.0, 3.0, 1.0, 4.0, 5.0]])
print(x.shape)

output = model(x)

print(output)

Sequential(
  (0): Linear(in_features=5, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=3, bias=True)
  (3): ReLU()
  (4): Linear(in_features=3, out_features=1, bias=True)
)
torch.Size([1, 5])
tensor([[0.4605]], grad_fn=<AddmmBackward0>)


In [13]:
import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(5, 4),
    nn.ReLU(),
    nn.Linear(4, 3),
    nn.ReLU(),
    nn.Linear(3, 1)
)

x = torch.tensor([[2.0, 3.0, 1.0, 4.0, 5.0]])

x1 = model[0](x)
print("After Linear 1:", x1)

x2 = model[1](x1)
print("After ReLU 1:", x2)

x3 = model[2](x2)
print("After Linear 2:", x3)

x4 = model[3](x3)
print("After ReLU 2:", x4)

x5 = model[4](x4)
print("Final output:", x5)

After Linear 1: tensor([[-3.5565, -1.2961, -0.3672, -2.5554]], grad_fn=<AddmmBackward0>)
After ReLU 1: tensor([[0., 0., 0., 0.]], grad_fn=<ReluBackward0>)
After Linear 2: tensor([[-0.1850,  0.2957, -0.4752]], grad_fn=<AddmmBackward0>)
After ReLU 2: tensor([[0.0000, 0.2957, 0.0000]], grad_fn=<ReluBackward0>)
Final output: tensor([[0.5132]], grad_fn=<AddmmBackward0>)


In [2]:
import torch
import torch.nn as nn

x = torch.tensor([
    [1.0, 2.0],
    [2.0, 1.0],
    [3.0, 2.0],
    [4.0, 1.0]
])

y = torch.tensor([
    [8.0],
    [7.0],
    [12.0],
    [11.0]
])

model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 3),
    nn.ReLU(),
    nn.Linear(3, 1)
)

prediction = model(x)

print(prediction)

loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01
)

loss = loss_fn(prediction, y)
print(loss)

loss.backward()

for name, param in model.named_parameters():
    print(name)
    print(param.grad)

optimizer.step()
print(model[4].bias)

tensor([[-0.3878],
        [-0.3540],
        [-0.5603],
        [-0.5266]], grad_fn=<AddmmBackward0>)
tensor(103.7652, grad_fn=<MseLossBackward0>)
0.weight
tensor([[0.0000, 0.0000],
        [5.4804, 3.1163],
        [6.8885, 3.9170],
        [0.0000, 0.0000]])
0.bias
tensor([0.0000, 2.0422, 2.5669, 0.0000])
2.weight
tensor([[ 0.0000, 12.7466, 14.0131,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])
2.bias
tensor([6.6492, 0.0000, 0.0000])
4.weight
tensor([[-37.6185,   0.0000,   0.0000]])
4.bias
tensor([-19.9144])
Parameter containing:
tensor([0.3537], requires_grad=True)


In [ ]:
for epoch in range(1200):

    # 1. Forward
    prediction = model(x)

    # 2. Loss
    loss = loss_fn(prediction, y)

    # 3. Calculate gradients
    loss.backward()

    # 4. Update weights
    optimizer.step()

    # 5. Clear gradients
    optimizer.zero_grad()

    if epoch % 100 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

print("Predictions:")
print(model(x))

print("\nActual:")
print(y)


Epoch: 0 Loss: 0.012455994263291359
Epoch: 100 Loss: 0.00965717900544405
Epoch: 200 Loss: 0.007486741058528423
Epoch: 300 Loss: 0.005803368054330349
Epoch: 400 Loss: 0.004499814473092556
Epoch: 500 Loss: 0.0034910449758172035
Epoch: 600 Loss: 0.0027076115366071463
Epoch: 700 Loss: 0.0020996674429625273
Epoch: 800 Loss: 0.0016296932008117437
Epoch: 900 Loss: 0.0012643771478906274
Epoch: 1000 Loss: 0.0009808208560571074
Epoch: 1100 Loss: 0.0007612708723172545
Predictions:
tensor([[ 7.9825],
        [ 6.9833],
        [11.9698],
        [10.9706]], grad_fn=<AddmmBackward0>)

Actual:
tensor([[ 8.],
        [ 7.],
        [12.],
        [11.]])
