In [6]:
import torch 

x = torch.tensor([1,2,3,4])

print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)

tensor([1, 2, 3, 4])
torch.Size([4])
1
torch.int64


In [4]:
import torch

x = torch.tensor([
    [1,5],
    [3,4]
])

y = torch.tensor([
    [4,3],
    [1,2]
])

print(x*y)
print(torch.matmul(x,y))

tensor([[ 4, 15],
        [ 3,  8]])
tensor([[ 9, 13],
        [16, 17]])


In [ ]:
"""
Exercise 2 — 2D Tensor
"""

import torch

x = torch.Tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(x)
print(x.ndim)
print(x.shape)
print(x[2][1])

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
2
torch.Size([3, 3])
tensor(8.)


In [5]:
s = "vinit pansare"

print(s.split())

['vinit', 'pansare']
