In [6]:
import torch 

x = torch.tensor([1,2,3,4])

print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)

tensor([1, 2, 3, 4])
torch.Size([4])
1
torch.int64


In [17]:
import torch

x = torch.tensor([
    [1,5],
    [3,4]
])

y = torch.tensor([
    [4,3],
    [1,2]
])

# print(x*y)
print(torch.matmul(x,y))

tensor([[ 9, 13],
        [16, 17]])


In [ ]:
"""
Exercise 2 — 2D Tensor
"""

import torch

x = torch.Tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(x)
print(x.ndim)
print(x.shape)
print(x[2][1])

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
2
torch.Size([3, 3])
tensor(8.)


In [16]:
"""
Exercise 3 — Element-wise operations
"""
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [26]:
x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

print(x)
print(x.shape)

y = x.reshape(3,2)
print(y.shape)
print(y)



tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.Size([3, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [5]:
s = "vinit pansare"

print(s.split())

['vinit', 'pansare']
