In [18]:
import torch

x = torch.tensor([
    [10,20,30],
    [40,50,60]
])

# print(x)
# print(x.shape)
# print(x.dtype)
# print(x.ndim)

print(x[0][1])#//20
print(x[0][0])#//10
print(x[1][2])#//60

tensor(20)
tensor(10)
tensor(60)


In [20]:
"""
Exercise for 2D tensors
"""
import torch

x = torch.tensor([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

print(x)
print(x.shape)
print(x.dtype)
print(x.ndim)
print(x[1])
print(x[2][1])



tensor([[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]])
torch.Size([3, 3])
torch.int64
2
tensor([20, 25, 30])
tensor(40)


In [ ]:
"""
tensors operations
"""

import torch 

x = torch.tensor([10,20,30])
y = torch.tensor([1,2,3])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print((x / y).dtype)


tensor([11, 22, 33])
tensor([ 9, 18, 27])
tensor([10, 40, 90])
tensor([10., 10., 10.])
torch.float32


In [29]:
"""
Matrix multipliation
"""

import torch

A = torch.tensor([
    [1,2],
    [3,4]
])

B = torch.tensor([
    [5,6],
    [7,8]
])

# print(A * B) /// Element-Wise multiplication

print(torch.matmul(A,B)) #/// Real matrix multiplication

tensor([[19, 22],
        [43, 50]])


In [39]:
"""
Reshaping Tensors
"""
import torch

x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

# print(x)
# print(x.shape)

y = x.reshape(3,2)
# y = x.reshape(6)
# y = x.reshape(1,6)
# print(y)
print(y.shape)

torch.Size([3, 2])


In [2]:
"""
dtype and conversions
"""
import torch

x = torch.tensor([1,2,3])
y = x.float()

# print(y)
# print(y.dtype)
# print(x)
print(x.dtype)

x = torch.tensor([1,2,3],  dtype=torch.float32)
print(x)
print(x.dtype)

torch.int64
tensor([1., 2., 3.])
torch.float32


In [ ]:
"""
Tensor to numpy
"""

x = torch.tensor([1,2,3])

y = x.numpy()
print(y)
print(y.dtype)


[1 2 3]
int64


In [ ]:
"""
numpy to torch
"""
import numpy as np

x = np.array([1,2,3])

y = torch.from_numpy(x)

print(x)
print(x.dtype)
print(type(x))


[1 2 3]
int64
<class 'numpy.ndarray'>


In [53]:
"""
Broadcasting 
"""
x = torch.tensor([1,2,3])

print(x + 10)

tensor([11, 12, 13])


In [61]:
"""
Tensors Creations
"""
torch.zeros(2, 3)
torch.ones(2, 3)
torch.rand(2, 3)
torch.arange(10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])