In [18]:
import torch

x = torch.tensor([
    [10,20,30],
    [40,50,60]
])

# print(x)
# print(x.shape)
# print(x.dtype)
# print(x.ndim)

print(x[0][1])#//20
print(x[0][0])#//10
print(x[1][2])#//60

tensor(20)
tensor(10)
tensor(60)


In [20]:
"""
Exercise for 2D tensors
"""
import torch

x = torch.tensor([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

print(x)
print(x.shape)
print(x.dtype)
print(x.ndim)
print(x[1])
print(x[2][1])



tensor([[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]])
torch.Size([3, 3])
torch.int64
2
tensor([20, 25, 30])
tensor(40)


In [22]:
"""
Matrix multiplication
"""

import torch 

x = torch.tensor([10,20,30])
y = torch.tensor([1,2,3])

print(x + y)
print(x - y)
print(x * y)
print(x / y)


tensor([11, 22, 33])
tensor([ 9, 18, 27])
tensor([10, 40, 90])
tensor([10., 10., 10.])
