In [18]:
import torch

x = torch.tensor([
    [10,20,30],
    [40,50,60]
])

# print(x)
# print(x.shape)
# print(x.dtype)
# print(x.ndim)

print(x[0][1])#//20
print(x[0][0])#//10
print(x[1][2])#//60

tensor(20)
tensor(10)
tensor(60)


In [20]:
"""
Exercise for 2D tensors
"""
import torch

x = torch.tensor([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

print(x)
print(x.shape)
print(x.dtype)
print(x.ndim)
print(x[1])
print(x[2][1])



tensor([[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]])
torch.Size([3, 3])
torch.int64
2
tensor([20, 25, 30])
tensor(40)


In [ ]:
"""
tensors operations
"""

import torch 

x = torch.tensor([10,20,30])
y = torch.tensor([1,2,3])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print((x / y).dtype)


tensor([11, 22, 33])
tensor([ 9, 18, 27])
tensor([10, 40, 90])
tensor([10., 10., 10.])
torch.float32


In [29]:
"""
Matrix multipliation
"""

import torch

A = torch.tensor([
    [1,2],
    [3,4]
])

B = torch.tensor([
    [5,6],
    [7,8]
])

# print(A * B) /// Element-Wise multiplication

print(torch.matmul(A,B)) #/// Real matrix multiplication

tensor([[19, 22],
        [43, 50]])


In [34]:
"""
Reshaping Tensors
"""
import torch

x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

print(x)
print(x.shape)

y = x.reshape(3,2)
print(y)
print(y.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])
